In [1]:
coefficient_matrix = [[2, 2, 1],[2, -1, 2], [1, -1, 2]]
constance_vector = [9, 6, 5]

In [2]:
import numpy as np

In [8]:
test_array = np.array([1, 4, 5, '8'],float)
test_array, type(test_array[3])

(array([1., 4., 5., 8.]), numpy.float64)

In [15]:
matrix =[[1, 2, 8],[1, 2, 5],[1, 5, 8]]
np.array(matrix, int).shape

(3, 3)

In [21]:
tensor =[
        [[1, 2, 8, 2],[1, 2, 5, 2],[1, 5, 8, 2]],
        [[1, 2, 8, 2],[1, 2, 5, 2],[1, 5, 8, 2]],
        [[1, 2, 8, 2],[1, 2, 5, 2],[1, 5, 8, 2]],
        ]

In [22]:
narray = np.array(tensor, int)
narray, narray.shape 

(array([[[1, 2, 8, 2],
         [1, 2, 5, 2],
         [1, 5, 8, 2]],
 
        [[1, 2, 8, 2],
         [1, 2, 5, 2],
         [1, 5, 8, 2]],
 
        [[1, 2, 8, 2],
         [1, 2, 5, 2],
         [1, 5, 8, 2]]]),
 (3, 3, 4))

In [31]:
a = np.array([[1, 2, 3, 4, 5],[6, 7, 8 , 9,10]], int)

In [38]:
print(a[:,2:])
print(a[1, 1:3]) 
print(a[1:3]) 


[[ 3  4  5]
 [ 8  9 10]]
[7 8]
[[ 6  7  8  9 10]]


In [82]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]], int)
a.shape
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

[[ 4]
 [ 8]
 [12]]
[[3 4]
 [7 8]]
[[2 3 4]]
[]


[[ 8]
 [12]]
[[7 8]]
[]
[]


[[12]]
[]
[]
[]


[]
[]
[]
[]


